/**
 * Asset configuration for the Charli PoV.
 *
 * Everything in this file is demonstration configuration. Swapping this file
 * (plus the sibling config modules) is what "configured for another asset"
 * means — no code changes.
 *
 * Source: Charli Demo Pack L9, L20, L36, L38-50, L160-161.
 */

export const asset = {
  id: "1-martin-place",
  name: "1 Martin Place",
  city: "Sydney",
  operatingModel: "After-hours digital concierge",
  modeLabel: "After-hours mode",
  footer: "Demonstration environment.",
  agentName: "Charli",
  tagline: "Your after-hours concierge",
} as const;

/** The only valid routing destinations. Source: L45-50. */
export const teams = [
  "After-Hours Building Support",
  "Building Support",
  "Security Desk",
  "Visitor Services",
  "Concierge Services",
] as const;

export type Team = (typeof teams)[number];

/** Reference number families. Source: L38-44. */
export const referenceFormats = {
  booking: { format: "BK-MP-####", example: "BK-MP-1042", label: "Room/space booking" },
  support: { format: "CH-MP-####", example: "CH-MP-3018", label: "Building/support request" },
  concierge: { format: "CS-MP-####", example: "CS-MP-4108", label: "Concierge-service request" },
  access: { format: "VA-MP-####", example: "VA-MP-1051", label: "Guest/access request" },
} as const;

export type ReferenceFamily = keyof typeof referenceFormats;

/**
 * Escalation tiers with the safety copy quoted verbatim from the brief (L31-34).
 *
 * This copy is returned by the `escalate` tool and emitted unchanged. It is
 * never generated by the model: paraphrasing an instruction to call 000 is the
 * one failure this demo cannot afford.
 */
export const escalationTiers = {
  emergency: {
    label: "Emergency",
    urgency: "Critical",
    team: "Building Support" as Team,
    template:
      "Please call 000 now and move to a safe area if you can. I'm alerting Building Support and recording your location as {location}.",
    locationFallback: "unconfirmed — tell me your level and I'll update it",
    handoffSummary:
      "Emergency alert raised with Building Support. Tenant advised to call 000 and move to a safe area. Location recorded.",
    priorityRule: "Emergency — immediate alert, no triage, no approval step.",
  },
  security: {
    label: "Security concern",
    urgency: "High",
    team: "After-Hours Building Support" as Team,
    template:
      "Thanks for flagging this. I'm connecting you with After-Hours Building Support now. Please remain in a safe, well-lit area.",
    handoffSummary:
      "Security concern handed to After-Hours Building Support for immediate attendance. Tenant advised to remain in a safe, well-lit area.",
    priorityRule: "Security — connect immediately, Security Desk notified in parallel.",
  },
  urgent_building: {
    label: "Urgent building issue",
    urgency: "High",
    team: "Building Support" as Team,
    template:
      "I've marked this as a priority for Building Support. Please keep clear of the affected area where possible.",
    handoffSummary:
      "Priority building issue logged for Building Support attendance. Tenant advised to keep clear of the affected area.",
    priorityRule: "Urgent building issue — priority flag, attend same shift.",
  },
  approval: {
    label: "Approval matter",
    urgency: "Standard",
    team: "Building Support" as Team,
    template:
      "I can help arrange that. Please provide {required_details} and I'll submit this to Building Support for approval.",
    handoffSummary:
      "Approval request prepared for Building Support review once required details are captured.",
    priorityRule: "Approval — capture required details, submit for approval, no auto-grant.",
  },
} as const;

export type EscalationTier = keyof typeof escalationTiers;
